FROM node:20

WORKDIR /server

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

# Copy the rest of the app
COPY . .

# Expose the port and start the server
EXPOSE 3000
CMD ["npm", "run", "dev"]
